### ISSUE TITLE
question: any plan to add koi x shinai kanojo?

### ISSUE THREAD

**Issue by 0xh3LL0** [number201724/GalGameTools#1]
i use both tools for both leyline from your repo, it seem doesnt work...
ToT

**Comment by number201724** [comment]
what's engine?

**Comment by 0xh3LL0** [comment]
amuse-craft / sofpal adv engine
i use your tools (both for Leyline) and it didnt work...
the script even saved in the same format as Leyline, its TEXT.DAT

**Comment by number201724** [comment]
The parsed Japanese (SHIFT-JIS codepage 932) file will be saved as a Simplified Chinese (GBK codepage 936);
you can modify the source code to convert to UNICODE encoding.

as:
text_print.c
CovtShiftJISToGB(cursc,conv_char,sizeof(conv_char));

**Comment by 0xh3LL0** [comment]
um, i dont think the issue is about the code page, either its chinese, japanese, or unicode, i can work with all of them...
here is the scenario file, in case you want to try it yourself [TEXT.7z](https://drive.google.com/file/d/0B4E8zrOX6ZdWOGZhVEowWVdLbTA/view?usp=sharing)

**Comment by 0xh3LL0** [comment]
marcussacana/UnisonShiftManager#2
