### ISSUE TITLE
the asm code in g00_test.cpp

### ISSUE THREAD

**Issue by hatikvah** [number201724/GalGameTools#2]
The g00 extraction algorithm in the function lzss_decompress() is a piece of cross-compiled ASM code, and where are the ASM codes from? I searched for the text in OllyDbg but found nothing. And I notice that there is a piece of ASM code annotated at the end of the file. What does that piece of code mean?

**Comment by number201724** [comment]
I copied it from the code decrypted in the engine, and which game I forgot.
