### ISSUE TITLE
Siglus engine word wrap

### ISSUE THREAD

**Issue by vnlovers** [number201724/GalGameTools#3]
How to add word wrapping support? As you can see, insert code "\n" not work. 
![Screenshot_7](https://user-images.githubusercontent.com/43198042/55661916-33fb5400-5839-11e9-8827-82b7104e5775.png)

**Comment by number201724** [comment]
What is this engine？ u can try \r\r

**Comment by number201724** [comment]
try to\r\n

**Comment by vnlovers** [comment]
I tried it but it didn't work

**Comment by vnlovers** [comment]
If it possibly, can you add a line breaks function? For example, if there is '\n' in the text, then the text should move to the next string in the game. Just in SiglusEngine there is no wordwrapping function.
I just want ssinsert support '\n' line breaks.

**Comment by vnlovers** [comment]
I found another tools for fix this issues.
